- README.markdown
- manifests/init.pp
- manifests/install.pp
- manifests/params.pp
- spec/acceptance/ntp_install_spec.rb
- spec/classes/ntp_spec.rb
As described in MODULES-1479, certain FreeBSD base installations already include the base version of ntp and FreeBSD users don't want the ntp module to manage the package on these systems.
This PR uses ideas from PR #154 , which for whatever reason has stalled.
@sethlyons - Is this missing anything?
> (MODULES-1479) Add package_manage parameter

- README.markdown
these restrictions are needed if you want to install an ntpd that only acts as a client
1) disable global acces
2) allow localhost completly (usefull for just in time config changes via cli)
3) allow minimal access to the source servers
everything for IPv4 and IPv6
settings are based on http://support.ntp.org/bin/view/Support/AccessRestrictions
more and more reflectd NTP attackes are commen on the internet, so it is pretty dangerous to install a simple client without these settings. I guess they could be usefull for other people.
> extend Readme for a simple client

- README.markdown
- spec/classes/ntp_spec.rb
- templates/ntp.conf.erb
Removing equal sign as delimiter in ntp.conf for the logfile parameter.
Adding documentation of logfile parameter in README.
> Fixing logfile parameter.

- README.markdown
- manifests/init.pp
- manifests/params.pp
- spec/classes/ntp_spec.rb
- templates/ntp.conf.erb
Hi,
this patch enables two configuration options in ntp.conf : the broadcast mode (the simple way) and the disabling of authentication.
Would you mind envisaging to merge those changes ?
> Broadcast and auth

- templates/ntp.conf.erb
adjust the expression to ensure `127.127.1.0` is set only if target is running
under virtual environment or `udlc` is set.
if `server` pointed to `127.127.1.0` without `preferred_servers` settings, it
would try to sync with itself but not to the `server`.
> fix `is_virtual` detection issue

- manifests/params.pp
Stdlib 4.0.0 allows str2bool to take a bool as an argument;
unfortunately ntp still claims to work with stdlib >= 3.2.0
> (MODULES-1796) Fix stdlib 3.2.0 compatibility

- README.markdown
- manifests/params.pp
- templates/ntp.conf.erb
The UDLC should really only be used on machines with accurate clocks, and
this logic was reversed incorrectly.
This PR also allows the udlc setting to be overridden, whereas before it
was not.
> Fix PR #235 and make udlc configurable

- README.markdown
- manifests/init.pp
- manifests/params.pp
- templates/ntp.conf.erb
> Add fudge option

- README.markdown
- manifests/params.pp
Do not enable UDLC by default on baremetal (non-virtual) systems.
Baremetal systems might not serve as time-source at all.
UDLC is not a back-up for leaf-nodes (ntp client only)!
See http://support.ntp.org/bin/view/Support/UndisciplinedLocalClock
> No Undisciplined Local Clock by default

- CHANGELOG.md
- metadata.json
PE 3.7.0 is free of vendored modules chains, so we like that release.
And we like newer stdlib.
> Bump stdlib to 4.5.0

- README.markdown
- manifests/init.pp
- manifests/params.pp
- spec/classes/ntp_spec.rb
- templates/ntp.conf.erb
(MODULES-1925) ntp stepout, minpoll and maxpoll options should be added
Change options:
* panic - panic is not boolean, it is integer, actually
Add options:
* tinker - disable or enable tinker
* minpoll - to change ntpd send packages frequency
* maxpoll - to change ntpd send packages frequency
* stepout - to change stepout interval
Add tests, change readme.
> Add ntp stepout, minpoll and maxpoll options

- spec/spec_helper_acceptance.rb
Unpredictable acceptance test failures were caused by something (likely dhcp) restarting ntp during test runs. Adding code to the spec_helper_acceptance.rb to remove the ntp exit hook so that ntp doesn't get restarted during tests.
> fixes debian-based flakiness in acceptance tests

- manifests/params.pp
ntpd reports syntax errors on wheezy and jessie with the original
value, presumably creating a subtly broken config.
> (MODULES-2087) fix debian default config

- README.markdown
- manifests/params.pp
- metadata.json
Add support for Solaris 12.  Solaris 12's package names match Solaris 11 so it's fairly straight-forward.
> - add Solaris 12 support

- manifests/params.pp
- spec/acceptance/ntp_config_spec.rb
- spec/classes/ntp_spec.rb
Arch Linux has its own pool [1], it also ships a different default
drift file [2].
[1] https://bugs.archlinux.org/task/41700
[2] https://projects.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/ntp
> Update Arch Linux defaults

- manifests/params.pp
- spec/spec_helper_acceptance.rb
I've run this branch manually through jenkins and it was green: https://jenkins-modules.puppetlabs.com/view/2.%20linux%20only/view/ntp/view/master/
> Fix CI for PE.next

- README.markdown
- manifests/params.pp
- metadata.json
This reverts commit 158f33fe6098e615ebe91dc562b7c3d61cf06763.
> Revert "- add Solaris 12 support"

- README.markdown
- manifests/init.pp
- manifests/params.pp
- spec/classes/ntp_spec.rb
- templates/ntp.conf.erb
```
Manycast Options
tos [ceiling ceiling | cohort { 0 | 1 } | floor floor | minclock minclock
| minsane minsane]
This command affects the clock selection and clustering algo-
rithms.  It can be	used to	select the quality and quantity	of
peers used	to synchronize the system clock	and is most useful in
manycast mode.  The variables operate as follows:
```
> MODULES-2210 Add TOS Parameter

- manifests/params.pp
- spec/acceptance/ntp_install_spec.rb
- spec/acceptance/ntp_parameters_spec.rb
- spec/classes/ntp_spec.rb
Due to a change in behavior between Facter 1.x and 2.x, the
operatingsystemrelease fact is no longer a desireable determination
of Solaris release.  This work updates the module to use the
kernelrelease fact in place of operatingsystemrelease as it does not
change behavior and is likely a more accurate representation of the
version of Solaris being tested.
> Update Solaris support for newer Facter

- spec/classes/ntp_spec.rb
- templates/ntp.conf.erb
The newly added tos settings for the ntp.conf file do not work because of a typo in the ntp.conf.erb. if @minclock should be if @tos_minclock.
> fix for tos settings in ntp.conf template and spec file

- manifests/params.pp
- metadata.json
Having rebase issues, so re-forked and added the changes. Much easier.
For history - see https://github.com/puppetlabs/puppetlabs-ntp/pull/263
> Adding ::operatingsystem Amazon for Facter < 1.7.0 (cloud-init installs 1.6.18)

- manifests/params.pp
Fixes https://tickets.puppetlabs.com/browse/MODULES-1790
I hope my fit follow your stile-guide - if not, please let me know.
The only issue I am experiencing with OpenSuSE 13.2 is that puppet uses chkconfig to enable the service, but afaik the issue is addressed here: https://tickets.puppetlabs.com/browse/PUP-4697
> Fix MODULES-1790

- metadata.json
I noticed there was a warning on the Puppet Forge metadata quality score about license formatting. It should follow the SPDX format.
https://docs.puppetlabs.com/puppet/latest/reference/modules_publishing.html#write-a-metadatajson-file
http://spdx.org/licenses/
> Convert license string to SPDX format

- .travis.yml
- README.markdown
- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/ntp_spec.rb
Replaces PR #194 
Adds unit test and README update.
Removes ruby 1.8.7 and puppet 2.7 from travis-ci config.
> enhanced default configuration

- spec/acceptance/ntp_service_spec.rb
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=760616
> Adding bug workaround in tests for Debian 8

- README.markdown
- manifests/init.pp
- manifests/params.pp
- spec/classes/ntp_spec.rb
- templates/ntp.conf.erb
I need to be able to sign NTP packets and this enables the parameter.
> Enabled usage of the $ntpsigndsocket parameter, for socket signing.

- manifests/init.pp
- manifests/params.pp
- spec/classes/ntp_spec.rb
- templates/ntp.conf.erb
This parameter is used in some versions of NTPd (such as Novell DSfW) to
enable compatibility with W32Time.
> Add support for the authprov parameter

- README.markdown
- manifests/init.pp
- manifests/params.pp
- spec/classes/ntp_spec.rb
- templates/ntp.conf.erb
The ntp configuration supports some tokens for interfaces that shall be ignored.
Previously the module used the pattern 'wildcard' to indicate that ntp
shouldn't listen to any interface but those specified as listen interfaces.
In some circumstances this is not enough. This commit adds a new parameter
interfaces_ignore that allows to list all interfaces (or interface tokens
like all, ipv6, ipv6 etc.) that should be ignored (and overrides the wildcard token).
> Add parameter for interfaces to ignore

- README.markdown
- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- spec/acceptance/ntp_parameters_spec.rb
- templates/keys.erb
I need to distribute keys to our nodes. And this works for me.
> add key distribution

- README.markdown
- manifests/params.pp
- spec/acceptance/ntp_parameters_spec.rb
- spec/classes/ntp_spec.rb
The keys_file defaults to /etc/ntp/keys on many platforms, but the
packages do not create that directory. There is a parameter, config_dir
that can be used to manage this directory, though in our acceptance
tests there was a line that did an mkdir of this directory which was
removed in PR #314 and covered up the fact that the module would not
work by default on many platforms. This should get the tests working
again, and update the debian/ubuntu defaults to their documented
defaults.
Both Debian and Ubuntu actually specify /etc/ntp.keys as the default.
And freebsd, sles, opensuse, and archlinux.
RedHat is the only OS with /etc/ntp/keys as the true default, against
the ntpd standard.
> Use config_dir for keys_file

- .travis.yml
- spec/acceptance/nodesets/docker/centos-7.yml
- spec/acceptance/nodesets/docker/ubuntu-14.04.yml
As per internal conversations, this is a simple demonstration of running
the current acceptance tests on Centos and Ubuntu. This allows for
pre-merge testing and aims to help catch some obvious cross-OS issues
early.
> Demonstrate adding beaker acceptance tests to a module

- README.markdown
The NTP modules 'package_name' option only accepts an array of strings. The documentation on this is incorrect and states that the option accepts only a string. I have fixed this.
> [MAINT] Update README to amend incorrect package_name description

- templates/keys.erb
Letting the template file path get set is disruptive to environment
based test workflows, causing unnecessary events each time one
switches environment, e.g.:
Notice: /Stage[main]/Ntp::Config/File[/etc/ntp/keys]/content:
--- /etc/ntp/keys       2016-09-23 14:36:07.000000000 +0200
+++ /tmp/puppet-file20160923-14521-1j0zq8t      2016-09-23
20:16:06.000000000 +0200
@@ -1,4 +1,4 @@
-#
/etc/puppet/environments/production/puppet/forge/ntp/templates/keys.erb
+#
/etc/puppet/environments/foo/puppet/forge/ntp/templates/keys.erb
#
> Remove path to template file from keys.erb

- templates/step-tickers.erb
This patch keeps the existing behavior for environments without
preferred servers.  For environments with preferred servers
step-tickers now only contains the preferred ntp sources.
> MODULES-3898 - ntp step-tickers should honor preferred servers

- spec/spec_helper_acceptance.rb
Now that stdlib 4.13.0 has been released, we should be using the released
version. Also puppet-tea is not used. And the git code failed on several
platforms (rhel5, centos 5, oracle 5, sles 10, 12) with git not being
available.
> Revert changes to spec_helper_acceptance

- data/Solaris-11.yaml
- data/Solaris.yaml
The commit to params to data-in-modules got the Solaris
data backawards.
https://github.com/puppetlabs/puppetlabs-ntp/commit/5a6bfb71fe1f4796964400f2fc264c8094786d5c
> Reverse Solaris-11 and Solaris transpose fix

- README.markdown
General edit of the ntp module readme, in prep for localization work and adding docs strings to code.
Of note, I've (mostly) pulled out "valid values" from descriptions, but added data types at the front of the descriptions. These types appeared to cover valid values for the most part, and having them at the front of the description will make strings import easier and let the user know up front what they are dealing with.
> Loc+ strings edit

- README.markdown
- manifests/config.pp
- manifests/init.pp
- manifests/install.pp
- manifests/service.pp
Added strings to init.pp
Made a few very minor changes to the README.
> (MODULES-4225) add strings to ntp module

- README.markdown
Requested changes for localization:
* values such as true, false, undef in backticks
* Optional/Required, Data types, and Default values on new lines to reduce translation costs
* hard line breaks within sentences removed
* more consistent language around default exceptions (looking at you, AIX and Solaris).
@LarissaLane , pinging you to let you know these changes are PR'd. Asking modules team to review and merge.
> edit for localization

- manifests/init.pp
This has been made obsolete in puppet 4, and the comment is a left-over from when the `anchor` resources were removed.
> Remove anchor comment

- data/common.yaml
- manifests/init.pp
- templates/ntp.conf.epp
Added support for pool config for ntpd ( http://doc.ntp.org/4.2.6/manyopt.html )
> Added pool support

- templates/ntp.conf.epp
prior to this commit each new attribute added to the template was adding an empty line, causing restart and unnecessary service disruption
> (MODULES-3396) remove superfluous empty lines in ntp.conf

- README.markdown
Removing an extra single quote mark in the README file.
> Removing an extra quote from the README

- locales/ja/puppetlabs-ntp.po
- readmes/README_ja_JP.md
Adding both files will address phase 1 of localisation of a puppet
module. This will eventually allow customers to view specific strings in
Japanese.
> (MODULES-4647) - Adding a Japanese translated po file and README

- CHANGELOG.md
- metadata.json
Merging back changes into master from the 6.1.0 release.
> Release 6.1.0 mergeback

- data/Suse.yaml
The default location for the ntp driftfile on SUSE is
/var/lib/ntp/drift/ntp.drift
therefore /var/lib/ntp/drift is a directory, and the driftfile
is not created. This commit changes the location of the driftfile
for SUSE to the default location.
> [MODULES-4941] Correct driftfile for SUSE OS

- README.md
- data/common.yaml
- manifests/init.pp
- spec/acceptance/enable_mode7_spec.rb
- spec/classes/ntp_spec.rb
- templates/ntp.conf.epp
This change allows to enable NTP mode7, which is used by the deprecated ntpdc program, but is also used by the colltectd plugin ntp. Mode7 was disabled by default starting with ntp 4.2.8.
The default behavior is not changed.
> (MODULES-4168) Add option to enable NTP mode7

- hiera.yaml
- metadata.json
This change updates the hiera.yaml to version 5 and removes all complaints about this package from puppet version 4.10 runs.
> Update yaml to version 5

- templates/ntp.conf.epp
theres nothing stopping stats with 'disable monitor' from working, not sure why stats were dependent on monitor.
This is working as expected on my end, if theres some internal NTP property that this is in conflict with could you please let me know.
> allow monitor disabled while setting stat properties

- README.md
Previously, declaring the ntp class with leading double-colons was
a safety measure, for people on Puppet 3.  Since this module now
only works on Puppet 4, and the double-colon is unnecessary, this
commit removes pointless preceding double-colons from the examples.
> Remove preceding double-colons from example class declarations

- hiera.yaml
- metadata.json
Reverts puppetlabs/puppetlabs-ntp#394
Reverting due to the following issues:
- https://tickets.puppetlabs.com/browse/MODULES-5780
- https://tickets.puppetlabs.com/browse/MODULES-5775
> Revert "Update yaml to version 5"

- CHANGELOG.md
- metadata.json
This is a major version bump as the lower puppet version boundary has
been updated to 4.9.4. The reasoning for this is that Hiera 5 needs a
minimum puppet version of 4.9.4.
> (MODULES-5831) - Release Prep for NTP 7.0.0

- manifests/init.pp
udlc docs removed from udlc_stratum
newline 2 spacing style docs instead of oneliners
> Make documentation more readable.

- manifests/init.pp
Data types don't need to be in the comments. This should reduce puppet-strings generation warnings.
> strip data types out of puppet-strings comments

- manifests/config.pp
- manifests/install.pp
- manifests/service.pp
Since the ntp class contains the other ntp classes ntp::config,
ntp::install and ntp::service it is neither necessary nor useful for
these classes to inherit from the "main" ntp class.
Letting the classes ntp::config, ntp::install and ntp::service inherit
from ntp is also counter all recommendations in the Puppet
documentation. The puppetlabs-ntp module is widely regarded as a "poster
child" for designing Puppet modules and is often used as reference by
Puppet newcomers. It should not make use of deprecated and useless or
confusing patterns.
See also https://github.com/puppetlabs/puppet-docs/pull/801
> Don't use 'inherits' in config, install and service

- README.md
- data/common.yaml
- manifests/init.pp
- templates/ntp.conf.epp
Add 'tos orphan' parameter which replaces udlc for peer groups (ntp >= 4.2.2).
> add tos_orphan parameter

- CHANGELOG.md
- README.md
- data/common.yaml
- manifests/init.pp
- spec/classes/ntp_spec.rb
- templates/ntp.conf.epp
[https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/s2_configuring_the_burst_option](url)
22.16.10. CONFIGURING THE BURST OPTION
Using the burst option against a public server is considered abuse. Do not use this option with public NTP servers. Use it only for applications within your own organization.
To increase the average quality of time offset statistics, add the following option to the end of a server command:
burst
At every poll interval, when the server responds, the system will send a burst of up to eight packets instead of the usual one packet. For use with the server command to improve the average quality of the time-offset calculations.
> Add burst param

- README.md
In order for the link on the forge site to work for the reference.md file you must specify the absolute github url as the link.  This fixes that.
> Fix forge link to reference.md

- README.md
The anchor tag helps fix broken links — If the header text changes (gets localized) the link will brake.
>  (maint) Add HTML anchor tag

- data/common.yaml
- manifests/init.pp
- manifests/service.pp
- spec/classes/ntp_spec.rb
Hi, this is my first pull request to this project. Let me know any changes that I need to do.
This PR adds class parameters to modify service hasstatus and hasrestart atributes, that are currently fixed to true.
Motivation of this change is that under some circumstances, a service restarts fails as if ntp process was slowly to stop, and the new one starting can't bind to address / port.
```
puppet-agent[28907]: (/Stage[main]/Ntp::Config/File[/etc/ntp.conf]/content) content changed '{md5}401589661b64e90b77c9c7f3f6a88df8' to '{md5}d79f2e85f4b263535186c092f99ed5ff'
systemd[1]: Stopping LSB: Start NTP daemon...
ntp[29587]:  * Stopping NTP server ntpd
ntp[29587]:    ...done.
systemd[1]: Stopped LSB: Start NTP daemon.
systemd[1]: Starting LSB: Start NTP daemon...
ntp[29600]:  * Starting NTP …
```
> Service hasstatus and hasrestart atributes

- data/FreeBSD-family.yaml
FreeBSD ships a leapfile that the default configuration of the module can use.
All supported FreeBSD versions contain this file.
> Set the path of FreeBSD's leapfile

- manifests/config.pp
`disable_dhclient` is currently broken due to https://github.com/puppetlabs/puppetlabs-ntp/pull/491/files#r298050592
Two options:
- revert to `/files` in `context` (easier)
- use `incl` + `lens` (a tiny bit more efficient, but more verbose code)
> Fix disable_dhclient

- spec/classes/ntp_spec.rb
Because FacterDB does not contain AIX factsets except in 3.2 and 3.9, and PDK loads facter 2.5.1 at the highest, I forced a stub in for AIX support in the spec file for all the resources.
This caused it to fail classifying AIX as an unsupported OS, so I added a test block to cover it.
> forced facter 3.9 to ensure AIX testing occurs

- data/Solaris-family.yaml
Adding Hiera data specification for the Solaris family.
Intended to enable support for the [illumos](https://www.illumos.org/) operating system (based on OpenSolaris).
Since the family name is at a deeper level in the Hiera hierarchy, it should not interfere with other operating system based on Solaris.
This replaces and closes #541.
> Add Solaris family Hiera data

- .sync.yml
- .travis.yml
- metadata.json
We have struggled to reproduce an issue with tests failing on xenial. A quick solution is to use the Ubuntu `bionic` release instead of `xenial`.
> (IAC-615) Bump TravisCI test runner dist to bionic

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .gitpod.Dockerfile
- .gitpod.yml
- .pdkignore
- .rubocop.yml
- .sync.yml
- .travis.yml
- Gemfile
- metadata.json
Update pdk-templates for gitpod and codespaces support
pdk version: `1.18.1`
> pdksync - Update pdk-templates for gitpod and codespaces support

- data/common.yaml
- manifests/config.pp
- manifests/init.pp
I need the set custom permissions for the ntp logfile (debian hardening guidelines).
This pull request adds an option to change the default permissions for the logfile
> (MAINT) Make mode for logfile configurable

- data/common.yaml
- manifests/config.pp
- manifests/init.pp
The Puppet file resource `manifests/config.pp` assumes that the user and group `ntp` exist on all supported operating systems. This is not the case (at least) for AIX 7.1, AIX 7.2, and Solaris 11. This results in the Puppet agent run failing to modify the user and group permissions of `$ntp::logfile`.
I'm proposing that the user and group values be turned into parameters, with the default user and group in `data/common.yaml` remaining as `ntp` as to not break any existing configurations.
> Allow setting user and group permissions of the NTP logfile

- data/Solaris-11.yaml
Oracle Solaris 11.4 SRU 45.119.2 adds a new SMF service for NTP monitoring `svc:/network/ntp:monitor`.
This results in the ntp module failing with the following error:
```
Error: /Stage[main]/Ntp::Service/Service[ntp]: Could not evaluate: Failed to get the FMRI of the network/ntp service: The pattern 'network/ntp' matches multiple FMRIs! These are the FMRIs it matches: svc:/network/ntp:default, svc:/network/ntp:monitor
```
This change updates `ntp::service_name` to specifically reference the default instance.
> SMF service instance change in Oracle Solaris 11.4 SRU 45.119.2

- metadata.json
Prior to this commit the metadata.json file for this module listed OSs that are not supported by puppet agent as supported. This commit aims to refactor the metadata.json file to only list OSs that are supported by puppet agent.
In this commit:
Support for AIX 5.3 and 6.1 was removed.
The list of supported OSs can be found here:
https://puppet.com/docs/pe/2021.7/supported_operating_systems.html
> (MAINT) Removal of support for AIX 5.3 & 6.1

- types/poll_interval.pp
Hi Team
Just migrating over to using the ntp forge module, and found this little nit
`minpoll` should be allowed to be 3, per the ntp documentation https://doc.ntp.org/documentation/4.2.6-series/confopt/#command-options, and 3 is even described as the lower range in https://github.com/puppetlabs/puppetlabs-ntp/blob/main/manifests/init.pp#L105
> minimum value for poll interval should be 3, not 4

- .github/workflows/integration_test.yml
Prior to this commit, this module contained a set-output command in the integration_test.yml file. This is a deprecated github command that will stop working by the end of may.
This commit aims to update the command so that it does not break once the syntax is fully deprecated.
> (CONT-404) Address set-output deprecation

- .github/workflows/integration_test.yml
Prior to this commit, the integration test workflow had deprecation warnings because it was using the checkout v2 workflow rather than v3. This commit replaces v2 with v3
> (CONT-903) Use checkout@v3

- .github/workflows/nightly.yml
Fixes https://github.com/puppetlabs/puppetlabs-ntp/actions/runs/5008997369
Removes the `acceptance` job dependency from the `integration` job due to the likelihood of failed provisioning, resulting in unran integration tests.
> (maint) - remove `runs_on` input from integration job

- manifests/install.pp
Enable legacy SP3 repo so that we can leverage the old packages without any issues.
New release of SUSE 15 introduced new version SP4 which deprecated old packages where `ntp` is one of them. As the package is deprecated with SP4 repo so user will not able to install.
Due to package got deprecated from new repo, respective package manager is not able to install.
> (MAINT) - Enable legacy repo for SUSE 15 SP4

- spec/acceptance/integration_ntp_spec.rb
> Avoid hardcoding year values

- manifests/install.pp
Enable legacy SP5 repo so that we can leverage the old packages without any issues.
Add any additional context about the problem here. 
New release of SUSE introduced new version SP5 which deprecated old apache2-mod_php7 package. As the package is deprecated with old SP4 repo so user will not able to install.
Due to package got deprecated from new repo, respective package manager is not able to install. This also affects the modules that is using java internally as a dependency or to install packages.
> (CAT-1204) - CI pipeline fix for SLES OS

- manifests/install.pp
Bump sles-module-legacy product from 15.5 to 15.6 as 15.5 is no more available in SUSEConnect extensions. 
This resolves the nightly failures for SLES-15 (puppet-7 and puppet8)
Mention any related issues or pull requests.
> (CAT-2052) Bump sles-module-legacy from 15.5 to 15.6

- .github/workflows/integration_test.yml
- plans/acceptance/pe_server.pp
Replace centos-7 with ubuntu-2204-amd for integration tests since centos-7 is no longer supported in PE.
We cannot migrate to centos-8 or centos-9 since those have deprecated ntp in favour of chrony. Updated pe_server version from 2019.8.5 to 2021.7.9 since the older one did not support PE for Ubuntu 2404.
Mention any related issues or pull requests.
> (CAT-2090) Replace centos-7 with ubuntu-2204-amd for integration tests

- .fixtures.yml
- manifests/config.pp
- metadata.json
- spec/acceptance/ntp_user_and_daemon_opts_spec.rb
Add support for Debian 12
Add any additional context about the problem here. 
Mention any related issues or pull requests.
> (CAT-2100) Add support for Debian-12
