spec/acceptance/ntp_install_spec.rb
=> These tests are better covered by the existing unit tests.

README.markdown
1. Removed the "what this affects" section.
2. Made sure each parameter lists a data type and a default value.
3. Made sure the links in the README work and are accurate.
4. Updated the link in the Contributing section to point here:
https://docs.puppetlabs.com/forge/contributing.html
5. Updated the Limitations section to link to the list of supported
platforms.
6. General copyediting.
=> Updates the README file

README.markdown
Removed a subsection with my last update; forgot to update the table of contents. Phooey.
=> Update the README Table of Contents

README.markdown, manifests/init.pp, manifests/params.pp, spec/classes/ntp_spec.rb, templates/ntp.conf.erb
=> MODULES-1836 - Added support for peers

CHANGELOG.md, metadata.json
=> Release Prep 4.0.0

README.markdown, manifests/params.pp, metadata.json
After rebase it can be merged into master
=> Add Solaris 10 Support

README.markdown, manifests/init.pp, manifests/params.pp, spec/classes/ntp_spec.rb, templates/ntp.conf.erb
Add support for disabling kernel time discipline in ntp.conf
https://tickets.puppetlabs.com/browse/MODULES-2282
=> (#2282) Add support for 'disable kernel'

lib/puppet/parser/functions/ntp_dirname.rb, manifests/config.pp, spec/spec_helper.rb
And deprecate the ntp_dirname function.
=> Fix management of etc and unit test runtime

README.markdown
I made a few changes in the README. In case you're wondering which of these minor things I couldn't live with for the release, it was the ampersand. :-)
=> editorial changes for ntp 4.2.x release

README.markdown, manifests/init.pp, manifests/service.pp
To follow spirit of Puppet 4 parameter validation
=> (maint) change service_ensure data type to Enum

README.markdown, data/common.yaml, manifests/init.pp, spec/acceptance/noselect_servers_spec.rb, spec/classes/ntp_spec.rb, templates/ntp.conf.epp, templates/step-tickers.epp
This PR address https://tickets.puppetlabs.com/browse/MODULES-4278
=> MODULES-4278 - NTP module noselect feature

locales/puppetlabs-ntp.pot
This is adding a POT file for the module.
=> (FM-6116) - Adding POT file for metadata.json

manifests/init.pp, metadata.json, spec/classes/ntp_spec.rb
there is full archlinux support in this module since a longer time.
=> add archlinux to metadata.json

CHANGELOG.md, metadata.json
Prepping for releasing NTP version 6.1.0.
=> (FM-6133) - NTP 6.1.0 Release Prep

README.markdown, spec/classes/ntp_spec.rb
Adding documentation into the readme for the pool parameter.
Also adding a few tests to ensure that the parameter is working as
expected.
=> (FM-6137) - Adding tests and docs for 'pool'

README.markdown
This improve the README rendering on GitHub.
=> Add missing spaces to README.markdown

manifests/config.pp
=> Update permissions on the keys file

README.md
http://www.ntp.org/ntpfaq/NTP-s-algo.htm#Q-POLL-RANGE
=> (docs) fix the range for polls in README

metadata.json
Removing unsupported OS according to the following document:
https://docs.puppet.com/pe/latest/sys_req_os.html
=> Removing unsupported OS

CHANGELOG.md, metadata.json
Reverts https://github.com/puppetlabs/puppetlabs-ntp/pull/394 due to the following issues:
- https://tickets.puppetlabs.com/browse/MODULES-5780
- https://tickets.puppetlabs.com/browse/MODULES-5775
=> Release Prep for 6.4.1

manifests/init.pp, spec/classes/contains_spec.rb, spec/classes/ntp_spec.rb
if you don't stringify facts, the fact is_virtual is a real bool and cant be given to the function str2bool.
=> is_virtual fact is boolean and can't be given to str2bool

README.md, data/AIX.yaml, data/common.yaml, manifests/init.pp, spec/classes/ntp_spec.rb, templates/ntp.conf.epp
AIX's xntpd has a configuration parameter not currently provided for by the template. It would be handy for me if it did.
=> MODULES-6402: ntp: support xntpd's slewalways 

data/SLES-15.yaml
This PR simply adds the necessary data file in order to support SLE 15
=> Add support for SLES 15

.fixtures.yml, .rubocop.yml, .travis.yml, Gemfile, metadata.json, spec/default_facts.yml
(FM-7392) - Puppet 6 Testing Changes
pdk version: `1.7.0`
=> pdksync - (FM-7392) - Puppet 6 Testing Changes

metadata.json, spec/acceptance/ntp_config_spec.rb, spec/acceptance/ntp_install_spec.rb, spec/acceptance/ntp_parameters_spec.rb, spec/acceptance/ntp_service_spec.rb, spec/classes/ntp_spec.rb
=> (FM-7719) - Remove Amazon Linux and Arch Linux testing/support for ntp module

CHANGELOG.md, metadata.json
=> (MODULES-9099) Release Prep 8.0.0

.github/workflows/release.yml, .sync.yml, .travis.yml, Gemfile, Rakefile, metadata.json, spec/spec_helper.rb
"(IAC-365) updating tokens and dataset for honeycomb"
pdk version: `1.16.0`
=> pdksync - "(IAC-365) updating tokens and dataset for honeycomb"

.github/workflows/nightly.yml, .puppet-lint.rc, .sync.yml, Rakefile, examples/init.pp, manifests/config.pp, manifests/install.pp, manifests/service.pp, metadata.json, plans/acceptance/pe_server.pp, plans/acceptance/provision_integration.pp
(Maint) PDK Update
pdk version: `2.3.0`
=> pdksync - (Maint) PDK Update

.devcontainer/README.md, Gemfile, Rakefile, metadata.json
pdksync/remove_puppet_module_gems
pdk version: `2.5.0`
=> pdksync - (PDKSync) Removal of puppet_module_gems

.sync.yml, Gemfile, Rakefile, metadata.json, spec/acceptance/integration_ntp_spec.rb
CONT-494/pin_github_changelog_generator
pdk version: `2.5.0`
=> pdksync - (CONT-494) Pin github_changelog_generator and JSON gem versions

.devcontainer/devcontainer.json, .github/workflows/auto_release.yml, Rakefile, metadata.json
This PR includes 4 files modified by PDK Update:
1. .devcontainer/devcontainer.json -> fix json formatting issue
2. .github/workflows/auto_release.yml - update pdk release image
3. Rakefile - fix whitespace formatting
4. metadata.json - update pdk version/ref
=> (maint) - PDK Update

spec/default_facts.yml, spec/spec_helper.rb
(maint) - Replace legacy facts in spec/default_facts.yml
pdk version: `2.7.1`
=> pdksync - (maint) - Replace legacy facts in spec/default_facts.yml

.rubocop.yml, .vscode/extensions.json, Gemfile, Rakefile, metadata.json
=> (CAT-1746) - PDK Update

.github/workflows/release.yml, .gitignore, .pdkignore, .rubocop.yml, Gemfile, metadata.json, spec/spec_helper.rb
(PF-3525) - pdk update for module
pdk version: `3.2.0`
=> pdksync - (PF-3525) - pdk update for module
